# Generated by Django 2.2.5 on 2019-09-22 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djconnect', '0002_auto_20190922_0218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
